{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-operator.fullname" . }}-webhook-service
  labels:
    {{- include "loki-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  {{- with .Values.webhook.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.serviceType }}
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "loki-operator.selectorLabels" . | nindent 4 }}
{{- end }}
