{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rawfile-csi.fullname" . }}-node
  labels:
    {{- include "rawfile-csi.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
  jobLabel: "helm.sh/chart"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "rawfile-csi.selectorLabels" . | nindent 6 }}
      component: node
{{- end }}
