{{- define "defaults.ConfigMap" }}
{{- $config := include "resources.generateConfigMap" ( deepCopy $ ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}-config
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
data:
  config.yaml: |-
    {{- $config | trim | nindent 4 }}
{{- end }}

{{- range $key, $componentValues := $.Values.firehosePods -}}
{{- $componentName := $key }}

{{- $templateCtx := include "resources.mergeValues" (dict "Root" $ "componentName" $key ) | fromYaml }}

{{- $values := deepCopy $templateCtx.Pod }}

{{- $defaultConfigMap := include "defaults.ConfigMap" $templateCtx | fromYaml }}

{{- $templatedConfigMap := get (list $defaultConfigMap $templateCtx | include "utils.templateCollection" | fromYaml) "result" }}

{{- if and $values.enabled $values.configMap.enabled }}
---
{{ $templatedConfigMap | toYaml }}
{{- end -}}
{{- end -}}
