{{- define "templates.ConfigMap" }}
{{- $config := include "resources.generateConfigMap" ( deepCopy $ ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}-config
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
data:
  config.yaml: |-
    {{- $config | trim | nindent 4 }}
{{- end }}
