{{- define "templates.Service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}
  namespace: {{ .Root.Release.Namespace }}
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
spec:
  type: {{ .Pod.service.spec.type }}
  ports: []
  selector:
    {{- include "metadata.selectorLabels" $ | nindent 4 }}
{{- end }}

{{- define "templates.ServiceHeadless" }}
metadata:
  name: {{ printf "%s-headless" .__svc.metadata.name }}
spec:
  clusterIP: None
{{- end }}

{{- define "templates.ServiceP2P" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}-p2p-0
  labels:
    pod: '{{ include "metadata.fullname" $ }}-{{ .componentName }}-0'
    type: p2p # this label is used by the initContainer to select this service
    {{- include "metadata.labels" $ | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports: []
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: '{{ include "metadata.fullname" $ }}-{{ .componentName }}-0'
{{- end }}
