{{- define "defaults.ServiceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata.serviceAccountName" $ }}
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
    {{- with .Pod.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- range $key, $componentValues := $.Values.firehosePods -}}
{{- $componentName := $key }}

{{- $templateCtx := include "resources.mergeValues" (dict "Root" $ "componentName" $key ) | fromYaml }}

{{- $values := deepCopy $templateCtx.Pod }}

{{- $defaultServiceAccount := include "defaults.ServiceAccount" $templateCtx | fromYaml }}

{{- $templatedServiceAccount := get (list $defaultServiceAccount $templateCtx | include "utils.templateCollection" | fromYaml) "result" }}

{{- if $values.serviceAccount.create }}
---
{{ $templatedServiceAccount | toYaml }}
{{- end }}
{{- end }}
