{{- define "templates.Service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}
  namespace: {{ .Root.Release.Namespace }}
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
spec:
  type: {{ .Pod.service.spec.type }}
  ports:
  {{- range $name, $spec := .Pod.service.spec.ports }}
  {{- if not (empty $spec.port) }}
    - name: {{ $name }}
      targetPort: {{ $spec.targetPort | default $name }} # the name of the port on the container that we are routing to
      {{ (omit $spec "targetPort") | toYaml | nindent 6 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "metadata.selectorLabels" $ | nindent 4 }}
{{- end }}

{{- define "templates.ServiceHeadless" }}
metadata:
  name: {{ printf "%s-headless" .__svc.metadata.name }}
spec:
  clusterIP: None
{{- end }}
