{{- define "templates.ServiceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata.serviceAccountName" $ }}
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
    {{- with .Pod.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
