compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'arm'
  libc:
    - 'glibc'
    - 'musl'
