compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.4.1.cjs

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'arm'
  libc:
    - 'glibc'
    - 'musl'
