{
 "title": "Subgraph Availability Oracle",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(reconcile_runs_total{container=\"subgraph-availability-oracle\"},pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(reconcile_runs_total{container=\"subgraph-availability-oracle\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(reconcile_runs_total{pod=\"$pod\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total failed runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(reconcile_runs_err{pod=\"$pod\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total denied subgraphs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(denied_subgraphs_total{pod=\"$pod\", namespace=\"$namespace\"}[$__range])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{pod=\"$pod\",namespace=\"$namespace\"} |~ \"(ERRO|no backends available for method)\""
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Old", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Reconcile runs / 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "increase(reconcile_runs_total{pod=\"$pod\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "total runs"
    },
    {
     "expr": "increase(reconcile_runs_ok{pod=\"$pod\"}[1m])",
     "legendFormat": "ok runs"
    },
    {
     "expr": "increase(reconcile_runs_err{pod=\"$pod\"}[1m])",
     "legendFormat": "error runs"
    },
    {
     "expr": "increase(reconcile_runs_total{pod=\"$pod\"}[1m])",
     "legendFormat": "total runs (arb)"
    },
    {
     "expr": "increase(reconcile_runs_ok{pod=\"$pod\"}[1m])",
     "legendFormat": "ok runs (arb)"
    },
    {
     "expr": "increase(reconcile_runs_err{pod=\"$pod\"}[1m])",
     "legendFormat": "error runs (arb)"
    }
   ]
  },
  {
   "title": "IPFS requests / 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
   "targets": [
    {
     "expr": "increase(ipfs_cache_hits{pod=\"$pod\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "cache hits"
    },
    {
     "expr": "increase(ipfs_requests_total{pod=\"$pod\"}[1m])",
     "legendFormat": "total requests"
    },
    {
     "expr": "increase(ipfs_requests_total{pod=\"$pod\"}[1m])",
     "legendFormat": "cache hits (arb)"
    },
    {
     "expr": "increase(ipfs_cache_hits{pod=\"$pod\"}[1m])",
     "legendFormat": "total requests (arb)"
    }
   ]
  },
  {
   "title": "Availability Oracle uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(up{pod=\"$pod\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "total runs"
    }
   ]
  },
  {
   "title": "Availability Oracle uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "total runs"
    }
   ]
  },
  {
   "title": "Denied subgraphs / 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(denied_subgraphs_total{pod=\"$pod\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "total runs"
    },
    {
     "expr": "increase(denied_subgraphs_total{pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}