{{- $labels := include "app.labels" . }}
{{- range $lName, $dict := .Values.configMaps }}
{{- $fullName := printf "%s-%s" (include "app.fullname" $) $lName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
{{- if .preUpgradePod }}
{{- if .preUpgradePod.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
{{- end }}
data: {{ toYaml $dict.data | nindent 2 }}
{{- end }}
