{{- $componentName := "merger"}}
{{- $componentValues := deepCopy (index $.Values $componentName) -}}
{{- $commonValues := deepCopy $.Values.common -}}
{{- $values := fromYaml (include "firehose-evm.genericMerge" (list $commonValues $componentValues)) -}}
{{- $templateContext := dict "Root" $ "Pod" $values "componentName" $componentName }}

{{- if $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "firehose-evm.serviceAccountName" (deepCopy $templateContext) }}
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
    {{- with $values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
