{{- $values := $.Values.reader }}
{{- $componentName := "reader" }}
{{- $componentLabel := include "firehose-evm.componentLabelFor" $componentName }}
{{- if $values.enabled }}
{{- if $values.jwt.fromLiteral }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-jwt
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  jwt.hex: {{ $values.jwt.fromLiteral | b64enc }}
{{- end }}
{{- end }}
