{{- $values := .Values.reader }}
{{- $componentName := "reader" }}
{{- $componentLabel := include "firehose-evm.componentLabelFor" $componentName }}
{{- if $values.enabled }}
{{- $configHash := "" }}

{{/* Use the helper to merge additional flags and construct the template variables */}}
{{- $configToml := include "firehose-evm.mergeConfig" ( merge ( deepCopy .Values ) ( dict "componentName" $componentName ) ) -}}
{{- $configHash = sha256sum $configToml }}
{{- $readerConfig := include "firehose-evm.readerArgs" $values }}

{{/* Now onto the actual Statefulset for indexer */}}

{{- $jwtEnabled := or $values.jwt.existingSecret.name $values.jwt.fromLiteral }}
{{- $jwtSecretName := default (print (include "firehose-evm.fullname" .) "-" $componentName "-jwt") $values.jwt.existingSecret.name }}
{{- $jwtSecretKey := default "jwt.hex" $values.jwt.existingSecret.key }}

{{- $env := merge .Values.common.env $values.env }}
{{- $secretEnv := merge .Values.common.secretEnv $values.secretEnv }}

{{/* START StatefulSet */}}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "firehose-evm.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  serviceName: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-headless
  replicas: {{ $values.replicas }}
  volumeClaimTemplates:
    - metadata:
        name: reader
      spec:
        {{- toYaml $values.volumeClaimSpec | nindent 8 }}
    - metadata:
        name: reader-node
      spec:
        {{- toYaml $values.reader_node.volumeClaimSpec | nindent 8 }}
  template:
    metadata:
      annotations:
      {{- with $values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.configMap.enabled }}
        checksum/config.toml: {{ $configHash }} # this will automate restarts of Deployment Pods when config changes
      {{- else if not .Values.podAnnotations }}
        # Add an empty line to ensure annotations block is created if it does not exist
        {}
      {{- end }}
      labels:
        {{- include "firehose-evm.selectorLabels" . | nindent 8 }}
        {{- $componentLabel | nindent 8 }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firehose-evm.serviceAccountName" . }}
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default "60" }}
      initContainers:
      {{- if $values.initSnapshot.enabled }}
        - name: init-snapshot
          image: rclone/rclone:1.67.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              set -ex;

              # Define variables
              STAMP="{{ $values.dataDir }}/._download.stamp"
              SNAPSHOT_LOCATION="${SNAPSHOT_REMOTE_LOCATION}"
              
              # Check if STAMP file exists and matches the current SNAPSHOT_LOCATION
              if [[ -f "${STAMP}" && "$(cat "${STAMP}")" = "${SNAPSHOT_LOCATION}" ]]; then
                echo "Snapshot has not changed. Skipping download.";
                exit 0;
              fi

              # Check if {{ $values.dataDir }} path has data in it
              if [ "$(ls -A {{ $values.dataDir }})" ]; then
                echo "Data already exists in {{ $values.dataDir }}. Checking if snapshot needs to be updated.";
              fi

              # Perform the rclone copy
              if ! rclone -v --progress --checkers 16 --transfers 16 --s3-chunk-size 16M --config /config/rclone copy ${SNAPSHOT_REMOTE_LOCATION} {{ $values.dataDir }}/; then
                echo "rclone copy failed";
                exit 1;
              fi;

              # Find the tar file (assuming there is only one) and extract it;
              TAR_FILE=$(ls {{ $values.dataDir }}/*.tar.zst);
              TMP_DIR="{{ $values.dataDir }}/._tmp_extract"
              mkdir -p "$TMP_DIR"

              if tar -xzvf "$TAR_FILE" -C "$TMP_DIR"; then
                mv "$TMP_DIR"/* "{{ $values.dataDir }}/"
                rm -rf "$TMP_DIR"
              else
                echo "Extraction failed. Cleaning up..."
                rm -rf "$TMP_DIR"
                exit 1
              fi

              # Record the current SNAPSHOT_LOCATION in the STAMP file
              echo "${SNAPSHOT_LOCATION}" > "${STAMP}";

          env:
          {{- with $values.initSnapshot.env }}
          {{- range $key, $val := .}}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
          - name: rclone-config
            mountPath: /config/rclone
            subPath: rclone.conf
          - name: reader-node
            mountPath: {{ $values.dataDir }}
      {{- end }}
      {{- if $values.p2pNodePort.enabled }}
        - name: init-nodeport
          image: "{{ $values.p2pNodePort.initContainer.image.repository }}:{{ $values.p2pNodePort.initContainer.image.tag }}"
          imagePullPolicy: {{ $values.p2pNodePort.initContainer.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - sh
            - -c
            - >
              set -ex;
              export EXTERNAL_PORT=$(kubectl get services {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-p2p-0 -o jsonpath='{.spec.ports[0].nodePort}');
              export EXTERNAL_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}');
              export EXTERNAL_IP=${EXTERNAL_IP:-$(curl --silent v4.ident.me)};
              cp /config/config.yaml /etc/config/config.yaml;
              sed -i "s|EXTERNAL_PORT|\"$EXTERNAL_PORT\"|g" /etc/config/config.yaml;
              sed -i "s|EXTERNAL_IP|$EXTERNAL_IP|g" /etc/config/config.yaml;
              cat /etc/config/config.yaml;
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: configmap
              mountPath: /config
              readOnly: true
      {{- end }}
      containers:
        - name: {{ $componentName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          args:
            {{- if $values.p2pNodePort.enabled }}
            - "start"
            - "-c"
            - "/etc/config/config.yaml"
            {{- else }}
            - "start"
            - "-c"
            - "/config/config.yaml"
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/usr/local/bin/eth-maintenance"]
          ports:
          {{- range $port := $values.service.ports }}
          - name: {{ $port.name }}
            containerPort: {{ $port.containerPort }}
            protocol: {{ $port.protocol | default "TCP" }}
          {{- end }}
          {{- if $values.p2pNodePort.enabled }}
          - name: eth66-udp-p2p
            containerPort: {{ include "reader.p2pPort" $values }}
            protocol: UDP
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with $env }}
          {{- range $key, $val := .}}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- with $secretEnv }}
          {{- range $key, $val := .}}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.secretName | quote }}
                  key: {{ $val.key | quote }}
                  optional: false
          {{- end }}
          {{- end }}
          {{- with $values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: reader
              mountPath: "/var/lib/fireeth"
            - name: reader-node
              mountPath: {{ $values.dataDir }}
            - name: configmap
              mountPath: /config
              readOnly: true
            {{- if $jwtEnabled }}
            - name: jwt
              mountPath: /jwt
            {{- end }}
            {{- if $values.p2pNodePort.enabled }}
            - name: config
              mountPath: /etc/config
            {{- end }}
      volumes:
        - name: reader
          persistentVolumeClaim:
            claimName: reader
        - name: reader-node
          persistentVolumeClaim:
            claimName: reader-node
        - name: configmap
          configMap:
            {{- if .Values.reader.configMap.enabled }}
            name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-config
            {{- else }}
            name: {{ .Values.reader.existingConfigMap }}
            {{- end }}
      {{- if $values.initSnapshot.enabled }}
        - name: rclone-config
          secret:
            secretName: rclone-config-secret
      {{- end }}
      {{- if $jwtEnabled }}
        - name: jwt
          secret:
            secretName: {{ $jwtSecretName }}
            items:
              - key: {{ $jwtSecretKey }}
                path: jwt.hex
      {{- end }}
      {{- if $values.p2pNodePort.enabled }}
        - name: config
          emptyDir: {}
      {{- end }}
{{- end }}
{{/* END StatefulSet */}}
