{{- $componentName := "grpc"}}
{{- $componentValues := deepCopy (index $.Values $componentName) -}}
{{- $commonValues := deepCopy $.Values.common -}}
{{- $values := fromYaml (include "utils.deepMerge" (list $commonValues $componentValues)) -}}
{{- $templateContext := dict "Root" $ "Pod" $values "componentName" $componentName }}
{{- $configToml := include "firehose-evm.generateConfigmap" ( deepCopy $templateContext ) }}
{{- $configHash := sha256sum $configToml }}

{{- if $values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-config
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- $configToml | trim | nindent 4 }}
{{-  end }}
