{
 "title": "Graph Indexing Status Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "pg_datasource", "label": "Store Data Source", "query": "postgres" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ethereum_chain_head_number,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block Ingestor Chain Head for ${namespace} (blocks/minute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ethereum_chain_head_number{job=\"graph-node-block-ingestor\", namespace=\"${namespace}\"}[$__rate_interval]) * 60",
     "legendFormat": "{{pod}}/{{network}}"
    }
   ]
  },
  {
   "title": "Graph Node JSON-RPC Errors for ${namespace} (errors/second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_rpc_errors{namespace=\"${namespace}\"}[$__rate_interval])",
     "legendFormat": "{{pod}}/{{provider}}/{{method}}"
    }
   ]
  },
  {
   "title": "Subgraph Sync Rate for ${namespace} (blocks/minute)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(deployment_head{namespace=\"${namespace}\"}[$__rate_interval]) * 60",
     "legendFormat": "{{pod}}/{{deployment}}"
    }
   ]
  },
  {
   "title": "Graph Node RPC Request Duration by Subgraph for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deployment_eth_rpc_request_duration{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{provider}}/{{deployment}}"
    }
   ]
  },
  {
   "title": "Active Subgraph Deployments for ${namespace}",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "-- grafana ignore\r\nselect\r\n  m.repository as repo,\r\n  g.name || (case\r\n        when g.pending_version = v.id then ' (P)'\r\n        when g.current_version = v.id then ' (C)'\r\n        else ' (U)' end) as subgraph_name,\r\n  d.deployment,\r\n  s.id as schema,\r\n  a.node_id,\r\n  d.synced::text,\r\n  n.name as network,\r\n  (n.head_block_number - d.latest_ethereum_block_number) as blocks_behind_network,\r\n  (case when n.name = 'mainnet' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'rinkeby' then ((n.head_block_number - d.latest_ethereum_block_number)/4)::text\r\n        when n.name = 'kovan' then ((n.head_block_number - d.latest_ethereum_block_number)/15)::text\r\n        when n.name = 'poa-core' then ((n.head_block_number - d.latest_ethereum_block_number)/12)::text\r\n        when n.name = 'ropsten' then ((n.head_block_number - d.latest_ethereum_block_number)/2)::text\r\n        else 'ø' end) as lag,\r\n        d.failed,\r\n        d.latest_ethereum_block_number,\r\n        a.paused_at\r\nfrom subgraphs.subgraph_deployment as d,\r\n     subgraphs.subgraph_deployment_assignment as a,\r\n     subgraphs.subgraph_version as v,\r\n     subgraphs.subgraph as g,\r\n     subgraphs.subgraph_manifest as m,\r\n     ethereum_networks  as n,\r\n     deployment_schemas as s\r\nwhere g.id = v.subgraph\r\n  and v.id in (g.pending_version, g.current_version)\r\n  and a.id = s.id\r\n  and s.id = d.id\r\n  and m.id = d.id\r\n  and v.deployment = d.deployment\r\n  /*and not d.failed*/\r\n  and n.name = s.network\r\n  and not a.node_id = 'removed'\r\norder by blocks_behind_network desc, subgraph_name;"
    }
   ]
  },
  {
   "title": "Subgraph Fatal Errors for ${namespace}",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  vid, cast(d.latest_ethereum_block_number as varchar) as block_num, encode(e.block_hash, 'hex') as block_hash, e.subgraph_id, e.message, a.node_id, e.deterministic, e.handler, e.created_at\nFROM subgraphs.subgraph_error as e,\n     subgraphs.subgraph_deployment as d,\n     subgraphs.subgraph_deployment_assignment as a\nWHERE\n    d.deployment = e.subgraph_id AND\n    a.id = d.id\nORDER BY vid DESC"
    }
   ]
  },
  {
   "title": "Subgraph Table Sizes for ${namespace}",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT table_schema,subgraph,total_bytes, pg_size_pretty(total_bytes) AS total\n  FROM (\n  SELECT *, total_bytes-index_bytes-coalesce(toast_bytes,0) AS table_bytes FROM (\n      SELECT nspname AS table_schema\n                , ds.subgraph\n              , sum(pg_total_relation_size(c.oid)) AS total_bytes\n              , sum(pg_indexes_size(c.oid)) AS index_bytes\n              , sum(pg_total_relation_size(reltoastrelid)) AS toast_bytes\n          FROM pg_class c\n          LEFT JOIN pg_namespace n ON n.oid = c.relnamespace\n            INNER JOIN deployment_schemas ds ON ds.name = n.nspname\n          WHERE relkind = 'r'\n            GROUP BY ds.subgraph,table_schema\n          \n  ) a\n) a ORDER BY total_bytes DESC;"
    }
   ]
  },
  {
   "title": "Graph Node Network Head Blocks for ${namespace}",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  head_block_number AS \"block_number\",\n  head_block_hash AS \"block_hash\"\nFROM ethereum_networks\nORDER BY name;"
    }
   ]
  },
  {
   "title": "Subgraph Node Assignments for ${namespace}",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "rawSql": "select node_id,\n       count(*) as num_assigned,\n       array_agg(id) as deployments\n  from subgraphs.subgraph_deployment_assignment\n group by node_id\n order by node_id asc;\n"
    }
   ]
  },
  {
   "title": "Store Connection Wait Time for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "store_connection_wait_time_ms{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{shard}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Store Connection Checkout Count for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "store_connection_checkout_count{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{shard}}/{{pool}}"
    }
   ]
  }
 ]
}