{
 "title": "Graph Query Performances",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(query_result_size_bucket,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Total QPS for $namespace",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(indexer_query_handler_seconds_count[$__rate_interval])) - sum(rate(indexer_query_handler_failed_total[$__rate_interval]))",
     "legendFormat": "Successful Qs (Instant)"
    },
    {
     "expr": "sum(rate(indexer_query_handler_failed_total[$__rate_interval]))",
     "legendFormat": "Failed Qs (Instant)"
    },
    {
     "expr": "sum(rate(indexer_query_handler_seconds_count[$__rate_interval])) - sum(rate(indexer_query_handler_failed_total[$__rate_interval]))",
     "legendFormat": "Successful Qs (Range)"
    },
    {
     "expr": "sum(rate(indexer_query_handler_failed_total[$__rate_interval]))",
     "legendFormat": "Failed Qs (Range)"
    }
   ]
  },
  {
   "title": "Total QPS by deployment for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (deployment) (rate(indexer_query_handler_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Query Cache Hit Rate for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(query_cache_status_count{cache_status=~\"shared|hit\",namespace=\"${namespace}\"}[$__rate_interval])) /\nsum(rate(query_cache_status_count{namespace=\"${namespace}\"}[$__rate_interval])) * 100",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Query Result Size Buckets (95% of Queries) for ${namespace}",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(query_result_size_bucket{namespace=\"${namespace}\"}[$__rate_interval])) by (le))",
     "legendFormat": "Query Size Bucket"
    }
   ]
  },
  {
   "title": "Query Result Size Buckets (All Queries) for ${namespace}",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(query_result_size_bucket{namespace=\"${namespace}\"}[$__rate_interval])) by (le))",
     "legendFormat": "Query Size Bucket"
    }
   ]
  },
  {
   "title": "Query Semaphore Wait Time for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_semaphore_wait_ms{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{shard}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Query Kill Rate by Shard for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "query_kill_rate{namespace=\"${namespace}\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Store Connection Wait Time for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "store_connection_wait_time_ms{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{shard}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Average Query Execution Time by Shard for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_effort_ms{namespace=\"${namespace}\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Store Connection Checkout Count for ${namespace}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "store_connection_checkout_count{namespace=\"${namespace}\"}",
     "legendFormat": "{{pod}}/{{shard}}/{{pool}}"
    }
   ]
  },
  {
   "title": "Indexer Error Rate (errors/s) by component for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(indexer_error{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}/{{code}}"
    }
   ]
  },
  {
   "title": "Top 10 Deployments by Queries for $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (deployment) (\n    increase(indexer_query_handler_seconds_count{namespace=\"$namespace\"}[$__range])\n  )\n)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Total Queries by deployment since last restart for $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sort_desc(\n  sum by (deployment) (\n    increase(indexer_query_handler_seconds_count{namespace=\"$namespace\"}[$__range])\n  )\n)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}