{{- $componentName := "index-builder" -}}
{{- $componentValues := deepCopy (index $.Values $componentName) -}}
{{- $commonValues := deepCopy $.Values.common -}}
{{- $values := fromYaml (include "firehose-evm.genericMerge" (list $commonValues $componentValues)) -}}
{{- if and $values.enabled $values.serviceMonitor.enabled -}}
{{- $defaultYaml := `
{{- $componentName := "index-builder" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
spec:
  jobLabel: {{ .Release.Name | quote }}
  selector:
    matchLabels:
      {{- include "firehose-evm.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics-fh
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
` -}}
{{- $defaultServiceMonitor := fromYaml (tpl $defaultYaml .) -}}

{{- $finalServiceMonitor := fromYaml (include "firehose-evm.serviceMonitorConfig" (list $defaultServiceMonitor $values.serviceMonitor)) -}}

{{- toYaml $finalServiceMonitor -}}
{{- end -}}
