{{- $values := $.Values }}
{{- /* If serviceMonitors enabled in chart-wide values */ -}}
{{- if $.Values.prometheus.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "subgraph-availability-oracle.fullname" . }}
  labels:
    {{- include "subgraph-availability-oracle.labels" . | nindent 4 }}
    {{- with $values.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "subgraph-availability-oracle.selectorLabels" . | nindent 6 }}
      serviceMonitorTarget: "true" # Additional label to prevent matching the headless service
  endpoints:
  - port: http-metrics
    path: /
    {{- with .Values.prometheus.serviceMonitors.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.serviceMonitors.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    honorLabels: true
    {{- if .Values.prometheus.serviceMonitors.relabelings }}
    relabelings:
    {{- toYaml .Values.prometheus.serviceMonitors.relabelings | nindent 8 }}
    {{- end }}
{{- end }}
