# Default values for listener-radio.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

# -- Pull secrets required to fetch the Image
imagePullSecrets: []

service:
  type: ClusterIP
  ports:
    # Valid keys are names of ports that are exposed by the Pod that (see templates/avalanche/statefulset.yaml)
    # -- Service Port to expose JSON-RPC interface on
    http-api: 7700
    # -- Service Port to expose Prometheus metrics on
    http-metrics: 2384

prometheus:
  serviceMonitors:
    # -- Enable monitoring by creating `ServiceMonitor` CRDs ([prometheus-operator](https://github.com/prometheus-operator/prometheus-operator))
    enabled: false
    labels: {}
    interval:
    scrapeTimeout:
    relabelings: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Set custom aliases for preconfigured commands in your environment
aliases: {}

# -- Image repository and tag
image:
  repository: ghcr.io/graphops/listener-radio
  pullPolicy: IfNotPresent
  # -- Overrides the image tag
  # @default -- Chart.appVersion
  tag: ""

env:
  # -- Subgraph endpoint to the Graphcast Registry
  REGISTRY_SUBGRAPH: "https://api.thegraph.com/subgraphs/name/hopeyen/graphcast-registry-mainnet"
  # -- Subgraph endpoint to The Graph network subgraph
  NETWORK_SUBGRAPH: "https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet"
  # -- Supported Graphcast networks: mainnet, testnet
  GRAPHCAST_NETWORK: "mainnet"
  # -- Comma separated static list of content topics to subscribe to
  RUST_LOG: "info,hyper=off,graphcast_sdk=info,waku_bindings=off,listener_radio=info"
  # -- For more details of other available env variables you can set, check https://docs.graphops.xyz/graphcast/radios/listener-radio#advanced-configuration

secretEnv: {}
  # PRIVATE_KEY:
  #   # -- Name of the secret that contains your PG password
  #   secretName:
  #   # -- Name of the data key in the secret that contains your PG password
  #   key:
  

# -- Additional CLI arguments to pass
extraArgs: []

# Increasing the grace termination period prevents Kubernetes
# from killing the node process prematurely. Premature shutdown
# can lead to data integrity issues
# -- Amount of time to wait before force-killing the process
terminationGracePeriodSeconds: 10

# -- Annotations for the `Pod`
podAnnotations: {}

# -- Pod-wide security context
podSecurityContext: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  #   ephemeral-storage: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  #   ephemeral-storage: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}

p2pNodePort:
  # -- Expose P2P port via NodePort
  enabled: false
  # -- Waku NodePort to be used. Must be unique.
  wakuPort: 60000
  # -- Discv5 NodePort to be used. Must be unique.
  discv5Port: 9000
  initContainer:
    image:
      # -- Container image to fetch nodeport information
      repository: lachlanevenson/k8s-kubectl
      # -- Container tag
      tag: v1.25.4
      # -- Container pull policy
      pullPolicy: IfNotPresent
