# Default values for subgraph-radio.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

# -- Pull secrets required to fetch the Image
imagePullSecrets: []

service:
  topologyAwareRouting:
    enabled: false
  type: ClusterIP
  ports:
    # Valid keys are names of ports that are exposed by the Pod that (see templates/subgraph-radio/statefulset.yaml)
    # -- Service Port to expose Prometheus metrics on
    http-metrics: 8090

rbac:
  # -- Specifies whether RBAC resources are to be created
  create: true
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  clusterRules:
     # Required to obtain the nodes external IP
    - apiGroups: [""]
      resources:
      - "nodes"
      verbs:
      - "get"
      - "list"
      - "watch"
  # -- Required ClusterRole rules
  # @default -- See `values.yaml`
  rules:
    # Required to get information about the serices nodePort.
    - apiGroups: [""]
      resources:
      - "services"
      verbs:
      - "get"
      - "list"
      - "watch"

prometheus:
  serviceMonitors:
    # -- Enable monitoring by creating `ServiceMonitor` CRDs ([prometheus-operator](https://github.com/prometheus-operator/prometheus-operator))
    enabled: false
    labels: {}
    interval:
    scrapeTimeout:
    relabelings: []

grafana:
  # -- Enable creation of Grafana dashboards. [Grafana chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana#grafana-helm-chart) must be configured to search this namespace, see `sidecar.dashboards.searchNamespace`
  dashboards: false
  # -- Must match `sidecar.dashboards.label` value for the [Grafana chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana#grafana-helm-chart)
  dashboardsConfigMapLabel: grafana_dashboard
  # -- Must match `sidecar.dashboards.labelValue` value for the [Grafana chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana#grafana-helm-chart)
  dashboardsConfigMapLabelValue: "1"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Set custom aliases for preconfigured commands in your environment
aliases: {}

# -- Image for subgraph-radio
image:
  repository: ghcr.io/graphprotocol/availability-oracle
  pullPolicy: IfNotPresent
  # -- Overrides the image tag
  # @default -- Chart.appVersion
  tag: ""

env:
  # -- The address of the Rewards Manager contract
  # REWARDS_MANAGER_CONTRACT: ""
  # -- The address of the subgraph availability manager contract
  SUBGRAPH_AVAILABILITY_MANAGER_CONTRACT: ""
  # -- Assigned index for the oracle, to be used when voting on SubgraphAvailabilityManager
  ORACLE_INDEX: ""
  # -- URL for the JSON-RPC endpoint
  RPC_URL: ""
  # -- URL for IPFS node
  ORACLE_IPFS: "https://ipfs.network.thegraph.com/"
  # -- RUST_LOG level
  RUST_LOG: "info"
  # -- Subgraph endpoint to The Graph network subgraph
  ORACLE_SUBGRAPH: ""
  # -- Graphql endpoint to the epoch block oracle subgraph used for fetching supported networks
  EPOCH_BLOCK_ORACLE_SUBGRAPH: ""
secretEnv:
  ORACLE_SIGNING_KEY:
    # -- Name of the secret that contains your Oracle Signing Key
    secretName:
    # -- Name of the data key in the secret that contains your Oracle Secret Key
    key:
  

# -- Additional CLI arguments to pass to `indexer-agent`
extraArgs: []

# -- Define livenessProbe as needed
livenessProbe: []

# -- Define readinessProbe as needed
readinessProbe: []

# Increasing the grace termination period prevents Kubernetes
# from killing the node process prematurely. Premature shutdown
# can lead to data integrity issues
# -- Amount of time to wait before force-killing the process
terminationGracePeriodSeconds: 10

# -- Annotations for the `Pod`
podAnnotations: {}

# -- Pod-wide security context
podSecurityContext: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  #   ephemeral-storage: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  #   ephemeral-storage: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
