globals:
  # -- Set a default storage class to use everywhere by default
  storageClassName: null

statefulNode:
  __enabled: true
  workload:
    __enabled: false
    replicaCount: 1

rpcdaemon:
  # -- Enable a Deployment of rpcdaemon that can be scaled independently
  __enabled: false
  workload:
    kind: Deployment

erigonDefaults:
  config:
    # -- Enable support for metrics
    metrics:
      enabled: true
      addr: 0.0.0.0
      port: 9102

    # -- Enable pprof interface support for profiling data
    pprof:
      enabled: true
      addr: 127.0.0.1
      port: 6070

    # -- Enable a NodePort for P2P support in node
    p2p:
      # -- Expose P2P port via NodePort
      enabled: false
      # -- protocol versions to use, as "protocolVersion: NodePort", i.e. "67: 30301"
      # -- NodePorts must be unique, or left as empty string "" to be obtained dynamically.
      #
      protocols:
        67: ""
        68: ""
      torrents:
        # -- Enable for torrents NodePort
        enabled: true
        # -- Specify nodePort to use or Leave null for dynamic
        nodePort: null

    # -- Provision or use an existing JWT secret
    # If it's enabled and neither existingSecret
    # nor fromLiteral are set, a random secret will
    # be generated and then re-used in the future
    jwt:
      # -- Provision or make use of a JWT secret for Node
      enabled: false
      # -- Load the JWT from an existing Kubernetes Secret. Takes precedence over `fromLiteral` if set.
      existingSecret:
        # -- Name of the Secret resource in the same namespace
        name: null
        # -- Data key for the JWT in the Secret
        key: null
      # -- Use this literal value for the JWT
      fromLiteral: null

    args:
      __separator: "="
      __prefix: "--"
      datadir: /storage
      db.read.concurrency: 16
      db.pagesize: 8KB
      rpc.batch.concurrency: 16
      rpc.returndata.limit: 4096000
      trace.maxtraces: 1000000
      healthcheck: "__none"
      http.enabled: true
      http.addr: 0.0.0.0
      http.port: 8545
      http.compression: true
      http.vhosts: "*"
      http.corsdomain: "*"
      http.api: "eth,debug,net,trace,erigon,engine"
      authrpc.addr: 0.0.0.0
      authrpc.port: 8551
      authrpc.vhosts: "*"
      authrpc.jwtsecret: ""
      ws: true
      ws.port: 8546
      ws.compression: true
      private.api.addr: '{{ $rpcdaemonEnabled | ternary "0.0.0.0:9090" "127.0.0.1:9090" }} @uses(.ComponentValues.rpcdaemon.__enabled as rpcdaemonEnabled)'
      metrics: '{{ $metrics.enabled | ternary (print "__none") nil }} @uses(.Self.config.metrics as metrics)'
      metrics.addr: '{{ $metrics.enabled | ternary (.addr | quote) nil }} @uses(.Self.config.metrics as metrics)'
      metrics.port: '{{ $metrics.enabled | ternary (.port | int) nil }} @uses(.Self.config.metrics as metrics)'
      pprof.addr: '{{ $pprof.enabled | ternary (.addr | quote) nil }} @uses(.Self.config.pprof as pprof)'
      pprof.port: '{{ $pprof.enabled | ternary (.port | int) nil }} @uses(.Self.config.pprof as pprof)'
      p2p.protocol: |
        {{ join "," (keys $p2p.protocols) }}
        @uses(.Self.config.p2p as p2p)
      p2p.allowed-ports: |
        {{- if $p2p.enabled }}
        {{- $strList := list }}
        {{- range $proto, $port := $p2p.protocols }}
        {{- if not (empty $port) }}
        {{- $strList = append $strList $proto }}
        {{- else }}
        {{- $strList = append $strList (printf "${EXTERNAL_PORT_%s}" $proto) }}
        {{- end }}
        {{- end }}
        {{- printf (join "," $strList) }}
        {{- else }}
        nil
        {{- end }}
        @uses(.Self.config.p2p as p2p)
      port: |
        {{ fail (.ComponentValues | toYaml) }}
        {{ $allowedPorts | splitList "," | first }}
        @requires(.Self.config.args[p2p.allowed-ports] as allowedPorts)
        @if(.Self.config.p2p.enabled)
      nat: '{{ $p2p.enabled | ternary "extip:${EXTERNAL_IP}" nil }} @uses(.Self.config.p2p as p2p)'
      torrent.port:
      torrent.download.slots: 6
      torrent.download.rate: 100mb
    argsOrder: []
  services:
    default:
      __enabled: false
      spec:
        ports: &svcPorts
          grpc-erigon:
            __enabled: '{{ $rpcdaemonEnabled | toYaml }} @uses(.ComponentValues.rpcdaemon.__enabled as rpcdaemonEnabled)'
            name: grpc-erigon
            port: 9090
            protocol: TCP
          http-metrics:
            __enabled: '{{ $metrics.enabled }} @uses(.Self.config.metrics as metrics)'
            name: http-metrics
            port: '{{ $metrics.port | int }} @uses(.Self.config.metrics as metrics)'
            protocol: TCP
          http-jsonrpc:
            __enabled: '{{ index $args "http.enabled" }} @uses(.Self.config.args as args)'
            name: http-jsonrpc
            port: '{{ index $args "http.port" | int }} @uses(.Self.config.args as args)'
            protocol: TCP
          ws-rpc:
            __enabled: '{{ index $args "ws" }} @uses(.Self.config.args as args)'
            name: ws-rpc
            port: '{{ index $args "ws.port" | int }} @uses(.Self.config.args as args)'
            protocol: TCP
          http-engineapi:
            __enabled: true
            name: http-engineapi
            port: '{{ index $args "authrpc.port" | int }} @uses(.Self.config.args as args)'
            protocol: TCP
    headless:
      __enabled: false
      spec:
        ClusterIP: None
        ports:
          <<: *svcPorts
    p2p:
      __enabled: true
      spec:
        ports:
          p2p-udp-67:
            __enabled: '{{ and ($p2p.enabled) (hasKey $p2p.protocols "67") }} @uses(.Self.config.p2p as p2p)'
            name: p2p-udp-67
            targetPort: null
            port: 30301
            nodePort: |
              {{- if and (hasKey $p2p.protocols "67") (not (empty (index $p2p.protocols "67"))) }}
              {{ index $p2p.protocols "67" | int }}
              {{- else }}
              null
              {{- end }}
              @uses(.Self.config.p2p as p2p)
            protocol: UDP
          p2p-tcp-67:
            __enabled: '{{ and ($p2p.enabled) (hasKey $p2p.protocols "67") }} @uses(.Self.config.p2p as p2p)'
            name: p2p-tcp-67
            targetPort: null
            port: 30301
            nodePort: |
              {{- if and (hasKey $p2p.protocols "67") (not (empty (index $p2p.protocols "67"))) }}
              {{ index $p2p.protocols "67" | int }}
              {{- else }}
              null
              {{- end }}
              @uses(.Self.config.p2p as p2p)
            protocol: TCP
          p2p-udp-68:
            __enabled: '{{ and ($p2p.enabled) (hasKey $p2p.protocols "68") }} @uses(.Self.config.p2p as p2p)'
            name: p2p-udp-68
            targetPort: null
            port: 30302
            nodePort: |
              {{- if and (hasKey $p2p.protocols "68") (not (empty (index $p2p.protocols "68"))) }}
              {{ index $p2p.protocols "68" | int }}
              {{- else }}
              null
              {{- end }}
              @uses(.Self.config.p2p as p2p)
            protocol: UDP
          p2p-tcp-68:
            __enabled: '{{ and ($p2p.enabled) (hasKey $p2p.protocols "68") }} @uses(.Self.config.p2p as p2p)'
            name: p2p-tcp-68
            targetPort: null
            port: 30302
            nodePort: |
              {{- if and (hasKey $p2p.protocols "68") (not (empty (index $p2p.protocols "68"))) }}
              {{ index $p2p.protocols "68" | int }}
              {{- else }}
              null
              {{- end }}
              @uses(.Self.config.p2p as p2p)
            protocol: TCP
          torrent-udp:
            __enabled: false
            name: udp-torrent
            containerPort: 42069
            protocol: UDP
          torrent-tcp:
            __enabled: true
            name: tcp-torrent
            containerPort: 42069
            protocol: TCP
  workload:
    __enabled: false
    kind: StatefulSet
    spec:
      volumeClaimTemplates:
        storage:
          accessModes: ["ReadWriteOnce"]
          storageClassName: '{{ default nil .Root.Values.globals.storageClassName }}'
          resources:
            requests:
              # -- The amount of disk space to provision for Erigon
              storage: 3Ti
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          partition: 0
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 101337
            runAsGroup: 101337
            fsGroup: 101337
          terminationGracePeriodSeconds: "60"
          volumes:
            tmp:
              emptyDir: {}
          initContainers:
            10-init-nodeport@common:
              __enabled: true
          containers:
            erigon:
              securityContext:
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              command:
                - sh
                - -ac
                - |
                  {{- $__parameters := dict
                    "map" $args
                    "orderList" ( $argsOrder | default list )
                  }}
                  {{- $argsList := include "common.utils.generateArgsList" $__parameters | fromYamlArray }}
                  set -ex;
                  exec erigon \
                  {{ join " \\\n" (initial $argsList) }}
                  {{ (last $argsList) }}
                  @uses(.Self.config.args as args)
                  @uses(.Self.config.argsOrder as argsOrder)
              ports:
                grpc-erigon:
                  __enabled: '{{ $rpcdaemonEnabled }} @uses(.ComponentValues.rpcdaemon.__enabled as rpcdaemonEnabled)'
                  name: grpc-erigon
                  containerPort: |
                    {{- $privateAddr := default nil (index $args "private.api.addr") }}
                    {{- if $privateAddr }}{{ $privateAddr | splitList ":" | last | int }}{{ else }}{{ nil }}{{ end }}
                    @uses(.ComponentValues.statefulNode.config.args as args)
                  protocol: TCP
                http-metrics:
                  __enabled: '{{ $metrics.enabled }} @uses(.Self.config.metrics as metrics)'
                  name: http-metrics
                  containerPort: '{{ $metrics.port | int }} @uses(.Self.config.metrics as metrics)'
                  protocol: TCP
                http-jsonrpc:
                  __enabled: '{{ index $args "http.enabled" }} @uses(.Self.config.args as args)'
                  name: http-jsonrpc
                  containerPort: '{{ index $args "http.port" }} @uses(.Self.config.args as args)'
                  protocol: TCP
                ws-rpc:
                  __enabled: '{{ index $args "ws" }} @uses(.Self.config.args as args)'
                  name: ws-rpc
                  containerPort: '{{ index $args "ws.port" }} @uses(.Self.config.args as args)'
                  protocol: TCP
                http-engineapi:
                  __enabled: true
                  name: http-engineapi
                  containerPort: '{{ index $args "authrpc.port" }} @uses(.Self.config.args as args)'
                  protocol: TCP
              volumeMounts:
                storage:
                  name: storage
                  mountPath: /storage
                tmp:
                  name: tmp
                  mountPath: /tmp
              readinessProbe:
                # This currently requires GRPCContainerProbe feature gate to be enabled on the kubelet
                # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe
                # https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
                grpc:
                  port: 9090 # named ports not supported yet by grpc probes
