{
 "title": "Graphcast Subgraph Radio",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "Arbitrum One : http://subgraph-radio.graph-arbitrum-one.svc.cluster.local:7700/api/v1/graphql, Arbitrum Sepolia : http://subgraph-radio.graph-arbitrum-sepolia.svc.cluster.local:7700/api/v1/graphql"
   }
  ]
 },
 "panels": [
  {
   "title": "POI Comparison Overview",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "field": "", "operator": "equals", "value": [ "" ] }
     ],
     "root_selector": "$.data.[*]",
     "source": "url",
     "type": "graphql",
     "url": "${network}",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "query {\n  data:comparisonResults{\n    deployment\n    resultType\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Number of Gossiping Indexers per Subgraph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_connected_peers"
    },
    {
     "expr": "graphcast_subgraph_radio_gossip_peers"
    }
   ]
  },
  {
   "title": "Message stats",
   "type": "stat",
   "description": "Average metrics based on each scrape\n- counter for received valid messages\n- gauge of cached messages\n\n- cached messages \n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphcast_subgraph_radio_validated_messages{}[30m])) * 60",
     "legendFormat": "Messages Validated/Minute"
    },
    {
     "expr": "sum(graphcast_subgraph_radio_cached_ppoi_messages{})",
     "legendFormat": "Messages In Store"
    },
    {
     "expr": "sum(graphcast_subgraph_radio_received_messages)",
     "legendFormat": "Received Messages"
    }
   ]
  },
  {
   "title": "Function Call Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "function_calls_concurrent" },
    {
     "expr": "histogram_quantile(0.95, sum(rate(function_calls_duration_bucket[5m])) by (le))"
    },
    { "expr": "rate(function_calls_count[5m])" }
   ]
  },
  {
   "title": "POI Comparison Results",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "root_selector": "$.data.[*]",
     "source": "url",
     "type": "graphql",
     "url": "${network}",
     "url_options": {
      "body_content_type": "application/json",
      "body_graphql_query": "query {\n  data:comparisonRatio{\n    deployment\n    blockNumber\n    senderRatio\n    stakeRatio\n  }\n}",
      "body_type": "graphql",
      "data": "",
      "method": "POST",
      "params": []
     }
    }
   ]
  },
  {
   "title": "Locally tracked Public POIs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_local_ppois_to_compare",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Number of diverged subgraphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "graphcast_subgraph_radio_diverging_subgraphs"
    }
   ]
  }
 ]
}