{{- $values := $.Values.nwaku }}
{{- $componentName := "nwaku"}}
{{- $componentLabel := include "nwaku.componentLabelFor" $componentName }}

{{- $nodekeyEnabled := or $values.nodekey.existingSecret $values.nodekey.fromLiteral }}
{{- $nodekeySecretName := default (print (include "nwaku.fullname" .) "-" $componentName "-nodekey") $values.nodekey.existingSecret.name }}
{{- $nodekeySecretKey := default "nodekey.hex" $values.nodekey.existingSecret.key }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nwaku.fullname" . }}
  labels:
    {{- include "nwaku.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  serviceName: {{ include "nwaku.fullname" . }}-headless
  replicas: {{ include "nwaku.replicas" $values }}
  selector:
    matchLabels:
      {{- include "nwaku.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        {{- toYaml $values.volumeClaimSpec | nindent 8 }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nwaku.selectorLabels" . | nindent 8 }}
        {{- $componentLabel | nindent 8 }}
        {{- with $values.extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nwaku.serviceAccountName" . }}
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default "60" }}
      volumes:
        - name: tmp # this is to provide a writable /tmp even with securityContext.readOnlyRootFilesystem=true
          emptyDir: {}
      {{- if $nodekeyEnabled }}
        - name: nodekey
          secret:
            secretName: {{ $nodekeySecretName }}
            items:
              - key: {{ $nodekeySecretKey }}
                path: nodekey.hex
      {{- end }}
      {{- if $values.p2pNodePort.enabled }}
        - name: env-nodeport
          emptyDir: {}
      {{- end }}
      initContainers:
      {{- if $values.p2pNodePort.enabled }}
        - name: init-nodeport
          image: "{{ $values.p2pNodePort.initContainer.image.repository }}:{{ $values.p2pNodePort.initContainer.image.tag }}"
          imagePullPolicy: {{ $values.p2pNodePort.initContainer.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - sh
            - -c
            - >
              set -ex;
              export EXTERNAL_PORT=$(kubectl get services -l "pod in (${POD_NAME}), type in (p2p)" -o jsonpath='{.items[0].spec.ports[0].nodePort}');
              export EXTERNAL_IP=$(kubectl get nodes "${NODE_NAME}" -o jsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}');
              export EXTERNAL_IP=${EXTERNAL_IP:-$(curl --silent v4.ident.me)};
              echo "EXTERNAL_PORT=$EXTERNAL_PORT" >  /env/init-nodeport;
              echo "EXTERNAL_IP=$EXTERNAL_IP"     >> /env/init-nodeport;
              cat /env/init-nodeport;
          volumeMounts:
            - name: env-nodeport
              mountPath: /env
      {{- end }}
      {{- if $values.initChownData.enabled }}
        - name: init-chown-data
          image: "{{ $values.initChownData.image.repository }}:{{ $values.initChownData.image.tag }}"
          imagePullPolicy: {{ $values.initChownData.image.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command:
            - sh
            - -ac
            - |
              set -ex;
              chown -R {{ $values.podSecurityContext.runAsUser }}:{{ $values.podSecurityContext.runAsGroup }} /storage;
              ls -lah /storage
          volumeMounts:
            - name: storage
              mountPath: "/storage"
      {{- end }}
      containers:
        - name: {{ $componentName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          command:
            - sh
            - -ac
            - |
            {{- if $values.p2pNodePort.enabled }}
              . /env/init-nodeport;
            {{- end }}
              set -ex;
              export NODEKEY=$(cat /nodekey/nodekey.hex);
              wakunode2 \
                --store=false \
              {{- if $values.p2pNodePort.enabled }}
                --nat=extip:${EXTERNAL_IP} \
                --tcp-port=${EXTERNAL_PORT} \
              {{- else }}
                --tcp-port={{ include "nwaku.p2pPort" $values }} \
              {{- end }}
              {{- if $nodekeyEnabled }}
                --nodekey=${NODEKEY} \
              {{- end }}
                --rest=true \
                --rest-address=0.0.0.0 \
                --rpc=true \
                --rpc-address=0.0.0.0 \
                --rpc-admin=true \
                --metrics-server-address=0.0.0.0 \
              {{- range $arg := $values.extraArgs }}
                {{- $arg | nindent 16 }} \
              {{- end }}
                --metrics-server=true 
          ports:
            - name: htpp-rest
              containerPort: 8645
              protocol: TCP
            - name: http-metrics
              containerPort: 8008
              protocol: TCP
            - name: http-jsonrpc
              containerPort: 8545
              protocol: TCP
            - name: http-ws
              containerPort: 8000
              protocol: TCP
            - name: udp-p2p
              containerPort: {{ include "nwaku.p2pPort" $values }}
              protocol: UDP
            - name: tcp-p2p
              containerPort: {{ include "nwaku.p2pPort" $values }}
              protocol: TCP
          volumeMounts:
            {{- if $nodekeyEnabled }}
            - name: nodekey
              mountPath: /nodekey
            {{- end }}
            {{- if $values.p2pNodePort.enabled }}
            - name: env-nodeport
              mountPath: /env
            {{- end }}
            - name: storage
              mountPath: /storage
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              port: http-jsonrpc
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with $values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $values.affinity $values.affinityPresets.antiAffinityByHostname }}
      affinity:
      {{- with $values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.affinityPresets.antiAffinityByHostname }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ $.Release.Name }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ $componentName }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
