{{- $values := $.Values.avalanche }}
{{- $componentName := "avalanche"}}
{{- $componentLabel := include "avalanche.componentLabelFor" $componentName }}
{{/* Finally, let's render the template and generate the ConfigMap resource */}}
{{- $configTemplate := .Values.configTemplate }}
{{- $configToml := print (tpl $configTemplate $) }}
{{/* We use a hash of the configuration to automate restarts of dependents */}}
{{- $avalancheNodeConfigHash := $configToml | sha256sum }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avalanche.fullname" . }}-{{ $componentName }}-config
  labels:
    {{- include "avalanche.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  config.toml: |
    {{ $configToml | nindent 4 }}