{{- $values := $.Values.avalanche }}
{{- $componentName := "avalanche"}}
{{- $componentLabel := include "avalanche.componentLabelFor" $componentName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalanche.fullname" . }}-{{ $componentName }}-headless
  labels:
    {{- include "avalanche.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  clusterIP: None # Headless service
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "avalanche.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if $values.service.topologyAwareRouting.enabled }}
  annotations:
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.GitVersion }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
  {{- end }}
  name: {{ include "avalanche.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "avalanche.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    serviceMonitorTarget: "true"  # Additional label to prevent matching the headless service above
spec:
  type: {{ $values.service.type }}
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "avalanche.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
{{- if $values.p2pNodePort.enabled }}
{{- $port := $values.p2pNodePort.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalanche.fullname" . }}-{{ $componentName }}-p2p-0
  labels:
    {{- include "avalanche.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    pod: {{ include "avalanche.fullname" . }}-{{ $componentName }}-0
    type: p2p # this label is used by the initContainer to select this service
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: tcp-p2p
      port: {{ include "avalanche.p2pPort" $values }}
      protocol: TCP
      targetPort: tcp-p2p
      nodePort: {{ $port }}
    - name: udp-p2p
      port: {{ include "avalanche.p2pPort" $values }}
      protocol: UDP
      targetPort: udp-p2p
      nodePort: {{ $port }}
  selector:
    {{- include "avalanche.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: "{{ include "avalanche.fullname" $ }}-{{ $componentName }}-0"
{{- end }}
