{{ define "templates.Secret" }}
{{- $secretName := printf "%s-%s-jwt" (include "metadata.fullname" $) .componentName -}}
{{- $secret := lookup "v1" "Secret" .Root.Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
type: Opaque
data:
  {{/* randAlphaNum 44 has slightly over 256 bits of entropy so it's enough */}}
  jwt.hex: |-
    {{- if not (empty .Pod.fireeth.jwt.fromLiteral) }}
    {{ .Pod.fireeth.jwt.fromLiteral | b64enc }}
    {{- else if $secret }}
    {{ index $secret.data "jwt.hex" }}
    {{- else }}
    {{ randAlphaNum 44 | sha256sum | lower | b64enc }}
    {{- end }}
{{- end }}
