{{ define "templates.Secret" }}
{{- $secretName := printf "%s-%s-jwt" (include "metadata.fullname" $) .componentName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" dict ) | fromYaml }}
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" dict ) | fromYaml }}
  labels:
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Root.Release.Namespace }}
type: Opaque
data:
  jwt.hex: |-
    {{ .Pod.fireeth.jwt.fromLiteral | b64enc }}
{{- end }}
