{{- define "templates.Service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" dict ) | fromYaml }}
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" dict ) | fromYaml }}
  {{- with .Pod.service.metadata }}
  {{- $labels = include "metadata.allLabels" ( set ( deepCopy $ ) "labels" .labels ) | fromYaml }}
  {{- $annotations = include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" .annotations ) | fromYaml }}
  {{- end }}
  labels:
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Root.Release.Namespace }}
spec:
  type: {{ .Pod.service.spec.type }}
  ports: []
  selector:
    {{- include "metadata.selectorLabels" $ | nindent 4 }}
{{- end }}

{{- define "templates.ServiceHeadless" }}
metadata:
  name: {{ .Pod.serviceName }}
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" dict ) | fromYaml }}
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" dict ) | fromYaml }}
  {{- with .Pod.service.metadata }}
  {{- $labels = include "metadata.allLabels" ( set ( deepCopy $ ) "labels" .labels ) | fromYaml }}
  {{- $annotations = include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" .annotations ) | fromYaml }}
  {{- end }}
  labels:
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Root.Release.Namespace }}
spec:
  clusterIP: None
{{- end }}

{{- define "templates.ServiceP2P" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" $ }}-{{ .componentName }}-p2p-0
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" dict ) | fromYaml }}
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" dict ) | fromYaml }}
  {{- with .Pod.serviceP2P.metadata }}
  {{- $labels = include "metadata.allLabels" ( set ( deepCopy $ ) "labels" .labels ) | fromYaml }}
  {{- $annotations = include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" .annotations ) | fromYaml }}
  {{- end }}
  labels:
    pod: '{{ include "metadata.fullname" $ }}-{{ .componentName }}-0'
    type: p2p # this label is used by the initContainer to select this service
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Root.Release.Namespace }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports: []
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}
    statefulset.kubernetes.io/pod-name: '{{ include "metadata.fullname" $ }}-{{ .componentName }}-0'
{{- end }}
