{{- define "templates.ServiceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata.serviceAccountName" $ }}
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" dict ) | fromYaml }}
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" dict ) | fromYaml }}
  {{- with .Pod.serviceAccount.metadata }}
  {{- $labels = include "metadata.allLabels" ( set ( deepCopy $ ) "labels" .labels ) | fromYaml }}
  {{- $annotations = include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" .annotations ) | fromYaml }}
  {{- end }}
  labels:
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Root.Release.Namespace }}
{{- end }}
