{{- define "templates.ServiceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata.serviceAccountName" $ }}
  labels:
    {{- include "metadata.labels" $ | nindent 4 }}
{{- end }}
