{{- define "templates.serviceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "metadata.fullname" . }}-{{ .componentName }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
  {{- with .Pod.serviceMonitor.metadata }}
  labels:
  {{- $labels := include "metadata.allLabels" ( set ( deepCopy $ ) "labels" .labels ) | fromYaml }}
  {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  annotations:
  {{- $annotations := include "metadata.allAnnotations" ( set ( deepCopy $ ) "annotations" .annotations ) | fromYaml }}
  {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  jobLabel: {{ .Root.Release.Name | quote }}
  selector:
    matchLabels:
      {{- include "metadata.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Root.Release.Namespace }}
  {{- with .Pod.serviceMonitor.spec.endpoints }}
  {{- if not (empty .) }}
  endpoints:
  {{- range $name, $spec := . }}
    - port: {{ $name }}
      {{ $spec | toYaml | nindent 6 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
