image: blockstack/envsubst:latest
command: ["/bin/sh", "-c"]
args:
  - |
    set -xe
    ENV_DIR="/env"

    if [ -d /env ]; then
      set -o allexport
      for env_file in "$ENV_DIR"/*; do
        [ -f "$env_file" ] && source "$env_file"
      done
      set +o allexport
    fi

    for file in /config-input/*.yaml; do
      envsubst < $file > /config-output/$(basename $file)
    done
volumeMounts:
  config:
    mountPath: /config-input
  config-processed:
    mountPath: /config-output
  env-dir:
    mountPath: /env
