{{- $values := $.Values.lighthouse }}
{{- $componentName := "lighthouse" }}
{{- $componentLabel := include "lighthouse.componentLabelFor" $componentName }}

{{- if $values.jwt.fromLiteral }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "lighthouse.fullname" . }}-{{ $componentName }}-jwt
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  jwt.hex: {{ $values.jwt.fromLiteral | b64enc }}
{{- end }}
