{{- $values := $.Values.reth }}
{{- $componentName := "reth" }}
{{- $componentLabel := include "reth.componentLabelFor" $componentName }}

{{- if and $values.jwt.fromLiteral (not $values.jwt.existingSecret.name) }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "reth.fullname" . }}-{{ $componentName }}-jwt
  labels:
    {{- include "reth.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  jwt.hex: {{ $values.jwt.fromLiteral | b64enc }}
{{- end }}
