{{- $values := $.Values.nethermind }}
{{- $componentName := "nethermind"}}
{{- $componentLabel := include "nethermind.componentLabelFor" $componentName }}

{{- if $values.jwt.fromLiteral }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "nethermind.fullname" . }}-{{ $componentName }}-jwt
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  jwt.hex: {{ $values.jwt.fromLiteral | b64enc }}
{{- end }}
