{
 "title": "nwaku single node dashboard",
 "description": "Basic metrics for a single running nwaku node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Libp2p PubSub Peers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_pubsub_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages (10m rate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total[10m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Waku Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (type)(waku_peers_errors)",
     "legendFormat": "peer {{type}}"
    },
    {
     "expr": "sum by (type)(waku_store_errors)",
     "legendFormat": "store {{type}}"
    },
    {
     "expr": "sum by (type)(waku_node_errors)",
     "legendFormat": "node {{type}}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pubsub Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "libp2p_pubsub_topics", "legendFormat": "Topics" },
    {
     "expr": "libp2p_pubsub_subscriptions_total",
     "legendFormat": "Subscriptions"
    },
    {
     "expr": "libp2p_pubsub_unsubscriptions_total",
     "legendFormat": "Unsubscriptions"
    }
   ]
  },
  {
   "title": "Waku Node Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    { "expr": "waku_node_errors", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "LibP2P Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "LibP2P PubSub Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "libp2p_pubsub_peers" }
   ]
  },
  {
   "title": "LibP2P Open Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(libp2p_open_streams)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "LibP2P Validations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_pubsub_validation_success_total",
     "legendFormat": "success "
    },
    {
     "expr": "libp2p_pubsub_validation_failure_total",
     "legendFormat": "failure "
    },
    {
     "expr": "libp2p_pubsub_validation_ignore_total",
     "legendFormat": "ignore "
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total",
     "legendFormat": "Attempts"
    },
    { "expr": "libp2p_failed_dials_total", "legendFormat": "Failed" },
    { "expr": "libp2p_successful_dials_total", "legendFormat": "Successful" }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes", "legendFormat": "Nim total memory: " },
    { "expr": "nim_gc_mem_occupied_bytes", "legendFormat": "Nim occupied memory: " },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes",
     "legendFormat": "Nim total heap: "
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes",
     "legendFormat": "  {{type_name}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Store Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "targets": [
    { "expr": "waku_store_peers" }
   ]
  },
  {
   "title": "Waku Store Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "targets": [
    { "expr": "waku_store_messages", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Waku Store Queries (10m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "increase(waku_store_queries[10m])"
    }
   ]
  },
  {
   "title": "Waku Store Errors (10m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_store_errors[10m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Store Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (le)(rate(waku_store_query_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Store Insert Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by (le)(rate(waku_store_insert_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Filter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Filter Peers",
   "type": "timeseries",
   "description": "Waku Filter Peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "targets": [
    { "expr": "waku_filter_peers" }
   ]
  },
  {
   "title": "Waku Filter Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "targets": [
    { "expr": "waku_filter_subscribers" }
   ]
  },
  {
   "title": "Waku Filter Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "targets": [
    { "expr": "waku_filter_errors", "legendFormat": "{{type}}: " }
   ]
  },
  {
   "title": "Lightpush",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Lightpush Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    { "expr": "waku_lightpush_peers" }
   ]
  },
  {
   "title": "Waku Lightpush Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    { "expr": "waku_lightpush_errors", "legendFormat": "{{type}}: {[instance}}" }
   ]
  }
 ]
}