{{- $values := $.Values.proxyd }}
{{- $componentName := "proxyd" }}
{{- $componentLabel := include "proxyd.componentLabelFor" $componentName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxyd.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "proxyd.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
  {{- range $portName, $portNumber := $values.service.ports }}
    - port: {{ $portNumber }} # the port we expose on the Service, user configurable
      targetPort: {{ $portName }} # the name of the port on the container that we are routing to
      protocol: TCP
      name: {{ $portName }}
  {{- end }}
  selector:
    {{- include "proxyd.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
