defaultLayer:
  workload:
    __enabled: true
    kind: Deployment
    spec:
      selector:
        matchLabels:
          app: test-workload
      template:
        metadata:
          labels:
            app: test-workload
        spec:
          containers:
            main:
              name: main
              image: nginx:latest

component1:
  __enabled: true
  workload:
    __enabled: true
    spec:
      replicas: 3

component2:
  __enabled: true
  workload:
    __enabled: true
    spec:
      replicas: 2

component1Overrides: {}
component2Overrides: {}
