{{- $values := $.Values.indexer }}
{{- $componentName := "indexer" }}
{{- $componentLabel := include "firehose-evm.componentLabelFor" $componentName }}
{{- if $values.enabled }}
{{- $configHash := "" }}
{{- if $values.configMap.enabled }}

{{/* Use the helper to merge additional flags and construct the template variables */}}
{{- $configToml := include "firehose-evm.mergeConfig" ( merge ( deepCopy .Values ) ( dict "componentName" $componentName ) ) -}}
{{- $configHash = sha256sum $configToml }}

{{/* START ConfigMap */}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-config
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
data:
  config.yaml: |-
    start:
      args:
        - index-builder
      flags:
{{- $configToml | trim | nindent 8 }}
{{/* END ConfigMap */}}
{{- end }}

{{/* Now onto the actual Statefulset for indexer */}}

{{- $env := merge .Values.common.env $values.env }}
{{- $secretEnv := merge .Values.common.secretEnv $values.secretEnv }}

{{/* START StatefulSet */}}
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}
  labels:
    {{- include "firehose-evm.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
  namespace: fh-eth-mainnet
spec:
  selector:
    matchLabels:
      {{- include "firehose-evm.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  serviceName: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-headless
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: indexer
      spec:
        {{- toYaml $values.volumeClaimSpec | nindent 8 }}
  template:
    metadata:
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firehose-evm.selectorLabels" . | nindent 8 }}
        {{- $componentLabel | nindent 8 }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firehose-evm.serviceAccountName" . }}
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $values.terminationGracePeriodSeconds | default "60" }}
      containers:
        - name: {{ $componentName }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          args:
            - "start"
            - "-c"
            - "/config/config.yaml"
          ports:
          {{- range $port := $values.service.ports }}
          - name: {{ $port.name }}
            containerPort: {{ $port.containerPort }}
            protocol: {{ $port.protocol | default "TCP" }}
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with $env }}
          {{- range $key, $val := .}}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- with $secretEnv }}
          {{- range $key, $val := .}}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.secretName | quote }}
                  key: {{ $val.key | quote }}
                  optional: false
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: indexer
              mountPath: "/var/lib/fireeth"
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            {{- if .Values.indexer.configMap.enabled }}
            name: {{ include "firehose-evm.fullname" . }}-{{ $componentName }}-config
            {{- else }}
            name: {{ .Values.indexer.existingConfigMap }}
            {{- end }}
        - name: indexer
          persistentVolumeClaim:
            claimName: indexer
{{- end }}
{{/* END StatefulSet */}}
