{{- $values := $.Values.arbitrum }}
{{- $componentName := "arbitrum" }}
{{- $componentLabel := include "arbitrum-classic.componentLabelFor" $componentName }}
{{- /* If serviceMonitors enabled in chart-wide values */ -}}
{{- if $.Values.prometheus.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arbitrum-classic.fullname" . }}
  labels:
    {{- include "arbitrum-classic.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "arbitrum-classic.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
      serviceMonitorTarget: "true" # Additional label to prevent matching the headless service
  endpoints:
    - port: http-metrics
      path: /debug/metrics/prometheus
      {{- with .Values.prometheus.serviceMonitors.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.prometheus.serviceMonitors.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: true
      {{- if .Values.prometheus.serviceMonitors.relabelings }}
      relabelings:
      {{- toYaml .Values.prometheus.serviceMonitors.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
