{
 "title": "Proxyd JSON-RPC Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(proxyd_backend_latest_block,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Inbound Req/s by status code for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code)(rate(proxyd_http_response_codes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s by backend for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (backend_name)(rate(proxyd_rpc_backend_http_response_codes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backend Req/s by method for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (method_name)(rate(proxyd_rpc_backend_http_response_codes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg latency by backend for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "proxyd_backend_avg_latency{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}/{{backend_name}}"
    }
   ]
  },
  {
   "title": "Block progression rate by backend for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(proxyd_backend_latest_block{namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}/{{backend_name}}"
    }
   ]
  },
  {
   "title": "Error rate by backend for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "proxyd_backend_error_rate{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}/{{backend_name}}"
    }
   ]
  },
  {
   "title": "Peer count by backend for $namespace",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "proxyd_consensus_backend_peer_count{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}/{{backend_name}}"
    }
   ]
  }
 ]
}