#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

helm-docs --template-files=./templates.gotmpl --template-files=README.md.gotmpl

for FILE in charts/**/README.md; do
   [ -f "$FILE" ] || continue
   git add $FILE
done