name: Add Labels

on:
  issues:
    types: [opened]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add Awaiting Triage Label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.LABELS_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'meta:awaiting-triage'