name: Update Helm Repository

on:
  release:
    types: [released]

  call-update-helm-repo-stable:
    uses: ./.github/workflows/update-helm-repo.yaml
    permissions:
      contents: write # for updating index.yaml
    with:
      repo: stable

  call-update-helm-repo-canary:
    uses: ./.github/workflows/update-helm-repo.yaml
    permissions:
      contents: write # for updating index.yaml
    with:
      repo: canary
